### ISSUE TITLE
displaying free / used memory on the Custom RPi Card

### ISSUE THREAD

**Issue by nabeelmoeen** [ironsheep/lovelace-rpi-monitor-card#13]
Total memory and %age used is available in the monitoring script output. Is there a way to customize the RPi custom card to pick and choose what sensor values to display vs. the defaults

**Comment by ironsheep** [comment]
Hmmm... not at this time.  You likely already know that you can see the values by tapping on the card, right?

So, what would you propose?  Sensors would have to be swapped out. So which would you replace with what?

**Comment by juancamilo87** [comment]
I think showing memory usage % is better than for example Model Interfaces. But it would be nice if the sensors displayed were configurable.

**Comment by nabeelmoeen** [comment]
maybe have RAM utilization vs. the SD Card size?
the disk space usage already appears, which is probably more relevant than the total disk space (although I understand, this may depend on my own usecase).

what i had in mind was something like the default 'glance' card, or @dangreco's [threedy_card
](https://github.com/dangreco/threedy) that allows you to pick which sensors you want displayed for the entity.

```
type: 'custom:threedy-card'
base_entity: sensor.ender_5
monitored:
  - Status
  - ETA
  - Hotend
  - Bed
  - Elapsed
  - Remaining
```
I may attempt this modification as I start learning a bit of programming and HA customization

**Comment by thijselblaso** [comment]
I like this as well. It would be nice to have the option to add memory and CPU usage. For me, this is more relevant than total disk space or OS.

**Comment by jsp196** [comment]
I created a template for memory percentage.  If you put the following into the Template editor, you'll see the result of each step.  I then just created a sensor based on the third one and added that to a vertical stack card using CPU usage, the new sensor, and then the RPi Monitor Card below those.

`free: {{ state_attr('sensor.rpi_monitor_omv', 'memory').free_mb }}
memory: {{ state_attr('sensor.rpi_monitor_omv', 'memory').size_mb }}
percent: {{ ((state_attr('sensor.rpi_monitor_omv', 'memory').free_mb |int / state_attr('sensor.rpi_monitor_omv', 'memory').size_mb |int ) * 100) | round(0)}}%`

**Comment by richardbabangida** [comment]
@jsp196  Thanks for the template! I created this template for used memory:

memory used in percentage:   
`{{ (100 / (state_attr('sensor.rpi_monitor_omv', 'memory').size_mb |int) * ((state_attr('sensor.rpi_monitor_omv', 'memory').size_mb |int ) - (state_attr('sensor.rpi_monitor_omv', 'memory').free_mb |int ))) | round(0) }}%`

**Comment by nabeelmoeen** [comment]
I've submitted a pull request for this change 
modified card and script output below
![rpi-monitor](https://user-images.githubusercontent.com/6676242/163111371-c9f602e1-3b4d-4a1f-874c-8371909d27a9.png)

**Comment by ironsheep** [comment]
This is merged into repo... working on more changes, then will release!

**Comment by ironsheep** [comment]
Changes committed. Feature appears in v1.2.6 and later
