### ISSUE TITLE
Not Get correct CPU Temperature

### ISSUE THREAD

**Issue by hellresistor** [ironsheep/lovelace-rpi-monitor-card#16]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Description of problem:**

Not Getting correct CPU Temperature
![Screenshot_2](https://user-images.githubusercontent.com/50468493/128613912-888fff6d-b14f-49ee-8c80-c8871e5e21a7.png)

I have an RPI4 4GB running debian 10 aarch64

**Comment by ironsheep** [comment]
Huh, unexpected...  Sorry to hear.

Can you run a tool like MQTT Explorer to see what values are being sent by the daemon script from this RPi?

**Comment by urielz** [comment]
I have the same issue. I'm not experienced with MQTT explorer, how do I look at the values? I can see this output...


`
{"name": "Rpi Temp Rpi4", "uniq_id": "RPi-Mon_temperature", "dev_cla": "temperature", "unit_of_measurement": "C", "stat_t": "~/monitor", "val_tpl": "{{ value_json.info.temperature_c }}", "~": "home/nodes/sensor/rpi-rpi4", "pl_avail": "online", "pl_not_avail": "offline", "ic": "mdi:thermometer", "avty_t": "~/status", "dev": {"identifiers": ["RPi-Mon"]}}`

**Comment by ironsheep** [comment]
@urielz you might take a look at youtube videos to help you understand MQTT Explorer: Something like: https://www.youtube.com/watch?v=pvuVjJ0AnrQ

Basically:
- connect to your MQTT Broker with MQTT Explorer
- navigate to the topic that is the RPi that seems to be reporting a bad temp. value
- inspec what the value is that is actually being reported.  If this value looks incorrect there is a problem with the daemon script running on your specific hardware or os version.  If this value looks to be correct then there is likely a problem with the RPi Lovelace cards interpretation of the value.  

Until we know which is the cause we don't know what needs to be addressed/fixed.  This make sense?

**Comment by nabeelmoeen** [comment]
hi, 
I have the same issue. one of my RPi 3B+ is working as expected, for the other I am getting incorrect results for the temp.
![image](https://user-images.githubusercontent.com/6676242/132348177-cc8536ea-f284-4199-8343-872afc360643.png)

The difference is:
- **Revision 1.2** is working as expected
- **Revision 1.3** is not working 
![image](https://user-images.githubusercontent.com/6676242/132348434-a845a2c9-11f8-463d-93f7-3d145c660eb7.png)

**Comment by ironsheep** [comment]
@nabeelmoeen ok, this is useful information...  Do you have the ubuntu install working correctly now?  If so, I'll be adding installation notes for ubuntu platforms to add what you've found...

**Comment by ironsheep** [comment]
@hellresistor , @urielz does the solution mentioned above (not having **vgencmd** installed?)

**Comment by nabeelmoeen** [comment]
> @nabeelmoeen ok, this is useful information...  Do you have the ubuntu install working correctly now?  If so, I'll be adding installation notes for ubuntu platforms to add what you've found...

Yes, it's working fine after installation of the 2 packages

**Comment by ironsheep** [comment]
OK, I've updated the Daemon README so that Ubuntu users will see the need to install this extra package!  

Oh, also, an updated version of the reporter daemon has just been released!

Thank you for reporting this! @nabeelmoeen

**Comment by urielz** [comment]
Coming back to this +3 years later! Thank you @ironsheep . It's working correctly now.

Note for Debian users: as with Ubuntu, you will need libraspberrypi-bin, however to install you need to add the repository to your sources (/etc/apt/sources.list), add:

deb http://archive.raspberrypi.org/debian/ *dist* main # where *dist* is your distribution

Also add gpg key otherwise the system will refuse to install from that source: 

> wget http://archive.raspberrypi.org/debian/raspberrypi.gpg.key -O raspberrypi.public.key
> sudo apt-key add raspberrypi.public.key
