### ISSUE TITLE
Show Available Upgrades

### ISSUE THREAD

**Issue by tdvantine** [ironsheep/lovelace-rpi-monitor-card#18]
**Is your feature request related to a problem? Please describe.**
Being able to monitor if there are any upgrades for the RPi without having to ssh into the Pi to check

**Describe the solution you'd like**
Be able to list the number of updates available, and have them separated out by system or security  

**Describe alternatives you've considered**
When running Ubuntu you can use the below command to list the number of updates, to which you can then use a command line sensor to pull the data into Home Assistant, however raspbian doesn't have the same ability to do so as easily.

**Additional context**
custom:multiple-entity-row design I have for a Ubuntu machine 
![custom:multiple-entity-row card](https://user-images.githubusercontent.com/56764154/148700134-4d9823f3-65d3-491b-b123-a69236274198.png)

Cronjob that runs
```
/usr/lib/update-notifier/apt-check 2>&1 | tee /home/homeassistant/.homeassistant/system_updates.out
```
and the command line sensors in config.yaml
```
  - platform: command_line
    name: System Updates
    scan_interval: 86400
    command: "cat /home/homeassistant/.homeassistant/system_updates.out | cut -d ';' -f 1"
```

```
  - platform: command_line
    name: Security Updates
    scan_interval: 86400
    command: "cat /home/homeassistant/.homeassistant/system_updates.out | cut -d ';' -f 2"
```

**Comment by ironsheep** [comment]
@tdvantine   This is interesting... let me see what I can do about this... Gonna be a couple of weeks at least... but more when I find out...

**Comment by tdvantine** [comment]
Any new news on this Ironwolf?

**Comment by ironsheep** [comment]
Finally have updates to the card and distribution working again.

Now I can consider doing this... More soonish...

**Comment by ironsheep** [comment]
My challenge is real estate on the card. Easier on the Full card than the Glance card.  

So I'll focus on pushing this thru the Daemon for now then I'll work on how to present it...

**Comment by ironsheep** [comment]
NOTE: see https://github.com/ironsheep/RPi-Reporter-MQTT2HA-Daemon/issues/71  for the latest notes and thinking...

**Comment by ironsheep** [comment]
Changes committed and appears in card v1.4.1 and later.
