### ISSUE TITLE
Font Color Adjustments

### ISSUE THREAD

**Issue by jsp196** [ironsheep/lovelace-rpi-monitor-card#19]
How / where do I go to adjust the font color for the Monitor Card?  I use a dark theme.  The attribute names all show up in white, but the values all show up in dark grey, which against a dark background are almost illegible.  I'd like to manually set them to something brighter.  Thanks!

**Comment by ironsheep** [comment]
The card is theme ready.  That is attribute values all use --primary-text-color while units of measure, etc. use --secondary-text-color.

However, that being said the Glance0layout card was correct in its use of these while the Full Layout was not.

I've just fixed the "Full" layout form of the card to use the correct values now.

**Comment by ironsheep** [comment]
Fixes are committed and will appear in v1.2.7 and later.
