### ISSUE TITLE
Custom element doesn't exist: rpi-monitor-card.

### ISSUE THREAD

**Issue by fesamper** [ironsheep/lovelace-rpi-monitor-card#27]
Hi,

I just installed lovelace-rpi-monitor-card and restarted home assistant but there is no way to use it:
If I go to dashboard->edit->add card->manual and I paste:
`type: 'custom:rpi-monitor-card'
entity: sensor.mirpisensor`
I get _Custom element doesn't exist: rpi-monitor-card._

I don't know what I'm missing.
RPI4-2GB, HA 2022.10.5- Supervisor 2022.10.0 - Frontend 20221010.0 - latest

**Comment by pwd-github** [comment]
Did you figure out how to do this?
