### ISSUE TITLE
Occasionally coloring seems to be incorrect 

### ISSUE THREAD

**Issue by ironsheep** [ironsheep/lovelace-rpi-monitor-card#3]
Our developer noticed this. Remembering here so we can fix it.

**Comment by ironsheep** [comment]
Changes committed to master. Fixes appear in v1.2.0 and later

**Comment by rapi3** [comment]
why it is colourful ? what is the reason and signification of this many colours ?
it will be nice to have only two colours here for connect(green)/disconnect(red)

![Screenshot_2020-11-06_09-42-32](https://user-images.githubusercontent.com/18531150/98345195-3ec92c80-200c-11eb-858b-f4ca1f7e6392.png)
