### ISSUE TITLE
How to set up hostname for the sensor when the Home Assistant is in docker container

### ISSUE THREAD

**Issue by mikebgrep** [ironsheep/lovelace-rpi-monitor-card#35]
Any help with this the home Assistant is in docker container and the hostname is Home Assistant how to get  Raspberry Pi hostname from the container i try with the original hostname of the pi and didn't work.
Edit: I try with the hostname and the error is same. The sensor is not discovered.

**Comment by ironsheep** [comment]
I'm not sure what the issue is here but all hostname / fully qualified domain name values can be overridden in the config.ini for the **RPi Reporter MQTT2HA Daemon**

**Comment by mikebgrep** [comment]
Hi again i found the issue I was not install the deamon.Now is works thank you

**Comment by ironsheep** [comment]
You are very welcome
