### ISSUE TITLE
Card Refresh rate slow or not refreshing at all

### ISSUE THREAD

**Issue by Anto79-ops** [ironsheep/lovelace-rpi-monitor-card#38]
Hey,

Great integration and use it lots!

I noticed recently, there have been quite few card updates. I noticed in the last one, the refresh rate of the card would be stuck unless I refresh the page. For example, see below. 

I've circled the uptime sensors, you can see the actual uptime sensor (top of page) does update every 2 minutes (my refresh rate) but the card is still stuck on when the page first loaded.

![image](https://user-images.githubusercontent.com/79593761/217668700-549dc547-13a9-4615-bddc-9848e9868ec4.png)

running 1.2.9.1. I don't think this was happening pre-1.2.9.1 and it was live updating

thanks for the integration!

**Comment by ironsheep** [comment]
@Anto79-ops yes, this is a known issue I'm working on  It appears there are crashes within library code underlying the card that I'm hunting down.  It should start working again as soon as these are fixed.  It's not easy meaning it's taking more time than I thought it should but I'm on it!

**Comment by Anto79-ops** [comment]
thank you, sir for your hard work in figuring this out!

**Comment by ironsheep** [comment]
Jeez, I'm releasing v1.3.2 after cleaning up the code... but this issue of the underlying exception happing in card update() is still haunting me...  the hunt continues... but the code is really much cleaner now... <shrug>

**Comment by ironsheep** [comment]
BTW- as a short-term workaround you should see that refreshing the page starts it all over again ... until the updates stop happening once more...  Just mentioning this in case it is in some way useful...

**Comment by Anto79-ops** [comment]
Thanks for the update! At least this is keeping your day interesting!

**Comment by BebeMischa** [comment]
Many thanks, @ironsheep , solved here ;-)

![afbeelding](https://user-images.githubusercontent.com/73079275/219106185-b65800b6-4121-4f59-9e14-d44d89593d9b.png)

**Comment by ironsheep** [comment]
Changes committed and appear in v1.4.0 and later
