### ISSUE TITLE
Different color for alerts

### ISSUE THREAD

**Issue by wokkeltje13** [ironsheep/lovelace-rpi-monitor-card#40]
The yellow is verry difficult to see when temp is high, could this also be changed to the orange or red?
![image](https://user-images.githubusercontent.com/57153640/218555778-7a1d74e6-d8c2-4a68-a8de-6278c8d613c1.png)

tnx

**Comment by ironsheep** [comment]
Color changes committed. Should appear in v1.3.2 and later.
