### ISSUE TITLE
disk use % not reporting correctly since 1.7.4

### ISSUE THREAD

**Issue by Anto79-ops** [ironsheep/lovelace-rpi-monitor-card#42]
### and have you...

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

### Version of RPi Monitor Card

Failling in 1.74, working in 1.72

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Browser and Operating system

Chrome/ Home Assistant

Hey the latest Dameon Update to 1.7.4 now makes a bogus disk use number in the HA lovelace card. The sensor is correct, so im thinking there is something in the card that needs to be tweaked. thanks

![image](https://user-images.githubusercontent.com/79593761/219907979-79ea90bc-7ad5-4001-9228-dbebc624a106.png)

thanks!

### Description of problem

incorrect disk use number on card only.

**Comment by ironsheep** [comment]
Thanks, your title is better! I filed this already as the daemon was feeding disk free and the card was correcting it to disk used.  The latest daemon is now delivering the correct value so the card needs to have this correction removed.

This is effectively a dupe of (#41)

Stephen

**Comment by Anto79-ops** [comment]
oh you're right. I just read your other at https://github.com/ironsheep/lovelace-rpi-monitor-card/issues/41

Ok, you're aware of this so I will close here.

Cheers.
