### ISSUE TITLE
The card always show the title

### ISSUE THREAD

**Issue by jvcsw** [ironsheep/lovelace-rpi-monitor-card#43]
### and have you...

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

### Version of RPi Monitor Card

1.3.3

### Is this a regression?

Yes. This used to work, but now it doesn't.

### Browser and Operating system

Browser: Firefox
OS: Windows

### Description of problem

The card always show the title even if you put:

        show_title: false

**Comment by jvcsw** [comment]
The same with:

**Comment by ironsheep** [comment]
Hrmf! Thanks for reporting this!

 I'm working on the card yet today to remove the disk-used calculations that no longer need to be in the card. (Latest Daemon update fixed the reported values.)  

I'll make sure this is working again in today's release.

**Comment by ironsheep** [comment]
Changes committed, appear in v1.3.4 and later

**Comment by jvcsw** [comment]
Thanks, now it works fine.
