### ISSUE TITLE
WIP releases showing up in my HACS feed

### ISSUE THREAD

**Issue by towo** [ironsheep/lovelace-rpi-monitor-card#46]
### and have you...

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

### Version of RPi Monitor Card

1.8.4

### Is this a regression?

No or unsure. This never worked, or I haven't tried before.

### Browser and Operating system

n/a

### Description of problem

HACS is getting spammed with WIP releases that are obviously meant as beta releases, please consider marking the releases as pre-release on GitHub, as that makes HACS not show the releases to users.

**Comment by ironsheep** [comment]
Please pardon the latest frequency of updates... This was a special effort requiring help from our card user community... 
The end result of the effort was new code was created to replace the use of external underlying utils which were failing for only part of the community.   This is also the first time we released monitoring of the MQTT daemon version (the 2nd part of this system) which needed community feedback by providing rapid turn-around to the changes as suggestions came in.

We are now back to full functionality and only formal releases as of v1.4.0 and later.   Thanks again for your patience!
