### ISSUE TITLE
External HDD showing on lovelace card

### ISSUE THREAD

**Issue by camui-alexandru** [ironsheep/lovelace-rpi-monitor-card#7]
I saw that behind the card, the external hdd storage is visible. Can you show it on the lovelace card ?

**Comment by ironsheep** [comment]
There are two lovelace cards 'full' and 'glance'.  Where are you thinking it should be shown and how would it appear?

All of the information you seek is already shown when you tap on the card itself in HA.  Tapping opens up the full detail view of the information from the Raspberry Pi. All of the information is shown already in this view.  

Think of this as each card brings forth things that are most important for that card type while some things will only be seen when tapping on the detail.

So, Yes, I'll gladly add configuration options when we find some really useful cases to do so or add some display when we think something is really missing.    So let me know what you are thinking.  Thanks for writing!

**Comment by rapi3** [comment]
Congratulation for this useful add-on.
If we have displayed model on full card maybe we can have also all the storage devices.
I also think that is more useful to have visible on full card all the storage devices with space used in % and not only the /
