### ISSUE TITLE
Add config value to completely hide card title (so can use in stack card)

### ISSUE THREAD

**Issue by ironsheep** [ironsheep/lovelace-rpi-monitor-card#8]
I'm trying to use this card in a horizontal/vertical stack card which has its own title.  Can the title for this card be hidden?

![image](https://user-images.githubusercontent.com/540005/93509649-44907480-f8dd-11ea-9efa-1ed59ef6eada.jpg)

**Comment by dbloom86** [comment]
Hey @ironsheep any news on this?

**Comment by ironsheep** [comment]
I have the new option in place in my code base, will be setting up layout testing this weekend.  Should have a new version early next week!

**Comment by ironsheep** [comment]
Changes committed to /master and appear in version v1.2.5 and later.

Introduced new  ` show_title:false` configuration directive

NOTE: When the card is shown without its title the time since last report value had to move. The following image shows the changes (see green arrows for the two card sizes.

![Screen_Shot_2020-09-26_at_15_44_14](https://user-images.githubusercontent.com/540005/94350969-3e9f3f80-0011-11eb-816b-487584023059.png)

**Comment by ironsheep** [comment]
@dbloom86 please let me know if this now works as you'd like.

**Comment by dbloom86** [comment]
@ironsheep that works like a charm! Super!

**Comment by ironsheep** [comment]
Great to hear!  Closing this then.  Enjoy!
