### ISSUE TITLE
CPU usage sensor

### ISSUE THREAD

**Issue by wokkeltje13** [ironsheep/lovelace-rpi-monitor-card#9]
It would be nice to have an extra sensor showing CPU usage (next to diskspace and temp)

**Comment by ironsheep** [comment]
While I appreciate your asking for this I'm not sure what good it would do since the data is reported once every 5 minutes while CPU Usage changes multiple times per second.  How would it be useful if the value is so far out of date?

**Comment by wokkeltje13** [comment]
most of my rPI are running static tasks with a constant CPU usage, sometimes things happen and CPU is going up or down. So I would use it more to see trends and to know something is wrong.

Is there not an average CPU usage available that can be used.

**Comment by jds11111** [comment]
Yeah, I would use it, too.  Sometimes my tiny pi will get slow to respond, and it would be nice to know if it were CPU usage related. However, given the 5min lag time, it might not work.

**Comment by ironsheep** [comment]
@wokkeltje13 ok, this has just been added.   The daemon project has just released v1.6.0 which offers the new sensor.

Enjoy!

**Comment by ironsheep** [comment]
@jds11111 update to latest daemon and you have new sensor.... (v1.6.0 and later)

**Comment by jds11111** [comment]
thanks!
